import { Author, Genre, Tag, Book, User, Review, ReadingBook, Collection } from '../types';

export const mockAuthors: Author[] = [
  { id: 1, name: 'Федор Достоевский', bio: 'Русский писатель, мыслитель, философ и публицист' },
  { id: 2, name: 'Лев Толстой', bio: 'Русский писатель и мыслитель, один из величайших писателей мира' },
  { id: 3, name: 'Антон Чехов', bio: 'Русский писатель, прозаик, драматург' },
  { id: 4, name: 'Михаил Булгаков', bio: 'Русский писатель, драматург, театральный режиссёр и актёр' },
  { id: 5, name: 'Александр Пушкин', bio: 'Русский поэт, драматург и прозаик' },
  { id: 6, name: 'J.K. Rowling', bio: 'British author, best known for Harry Potter series' },
  { id: 7, name: 'George Orwell', bio: 'English novelist and essayist, journalist and critic' },
  { id: 8, name: 'Harper Lee', bio: 'American novelist widely known for To Kill a Mockingbird' },
];

export const mockGenres: Genre[] = [
  { id: 1, name: 'Классика' },
  { id: 2, name: 'Фантастика' },
  { id: 3, name: 'Детектив' },
  { id: 4, name: 'Роман' },
  { id: 5, name: 'Драма' },
  { id: 6, name: 'Fantasy' },
  { id: 7, name: 'Dystopian' },
  { id: 8, name: 'Fiction' },
];

export const mockTags: Tag[] = [
  { id: 1, name: 'Бестселлер' },
  { id: 2, name: 'Классика' },
  { id: 3, name: 'Философия' },
  { id: 4, name: 'Психология' },
  { id: 5, name: 'Приключения' },
  { id: 6, name: 'Award-winning' },
  { id: 7, name: 'Modern classic' },
];

export const mockBooks: Book[] = [
  {
    id: 1,
    title: 'Преступление и наказание',
    textFile: '/books/crime-and-punishment.txt',
    coverFile: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    description: 'Роман об идее «сверхчеловека», которая приводит студента Родиона Раскольникова к преступлению. История внутренней борьбы и морального выбора.',
    authors: [mockAuthors[0]],
    genres: [mockGenres[0], mockGenres[4]],
    tags: [mockTags[1], mockTags[2]],
    averageRating: 4.8,
    reviewsCount: 342,
  },
  {
    id: 2,
    title: 'Война и мир',
    textFile: '/books/war-and-peace.txt',
    coverFile: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    description: 'Эпический роман-эпопея о русском обществе в эпоху наполеоновских войн. История любви, войны и поиска смысла жизни.',
    authors: [mockAuthors[1]],
    genres: [mockGenres[0], mockGenres[3]],
    tags: [mockTags[1], mockTags[0]],
    averageRating: 4.7,
    reviewsCount: 289,
  },
  {
    id: 3,
    title: 'Мастер и Маргарита',
    textFile: '/books/master-and-margarita.txt',
    coverFile: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
    description: 'Мистический роман о добре и зле, любви и предательстве. Дьявол приезжает в Москву 1930-х годов.',
    authors: [mockAuthors[3]],
    genres: [mockGenres[0], mockGenres[1]],
    tags: [mockTags[1], mockTags[2]],
    averageRating: 4.9,
    reviewsCount: 456,
  },
  {
    id: 4,
    title: 'Анна Каренина',
    textFile: '/books/anna-karenina.txt',
    coverFile: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400',
    description: 'Роман о трагической любви замужней женщины Анны Карениной и офицера Вронского на фоне жизни русского общества XIX века.',
    authors: [mockAuthors[1]],
    genres: [mockGenres[0], mockGenres[3], mockGenres[4]],
    tags: [mockTags[1], mockTags[3]],
    averageRating: 4.6,
    reviewsCount: 278,
  },
  {
    id: 5,
    title: 'Евгений Онегин',
    textFile: '/books/eugene-onegin.txt',
    coverFile: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400',
    description: 'Роман в стихах о молодом дворянине и его неразделённой любви. Энциклопедия русской жизни начала XIX века.',
    authors: [mockAuthors[4]],
    genres: [mockGenres[0], mockGenres[3]],
    tags: [mockTags[1]],
    averageRating: 4.5,
    reviewsCount: 198,
  },
  {
    id: 6,
    title: 'Harry Potter and the Philosopher\'s Stone',
    textFile: '/books/harry-potter-1.txt',
    coverFile: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=400',
    description: 'The first book in the Harry Potter series follows young wizard Harry as he discovers his magical heritage and attends Hogwarts.',
    authors: [mockAuthors[5]],
    genres: [mockGenres[5], mockGenres[7]],
    tags: [mockTags[0], mockTags[4], mockTags[6]],
    averageRating: 4.9,
    reviewsCount: 1203,
  },
  {
    id: 7,
    title: '1984',
    textFile: '/books/1984.txt',
    coverFile: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
    description: 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.',
    authors: [mockAuthors[6]],
    genres: [mockGenres[6], mockGenres[1]],
    tags: [mockTags[1], mockTags[6]],
    averageRating: 4.7,
    reviewsCount: 892,
  },
  {
    id: 8,
    title: 'To Kill a Mockingbird',
    textFile: '/books/mockingbird.txt',
    coverFile: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400',
    description: 'A novel about racial injustice and childhood innocence in the American South during the 1930s.',
    authors: [mockAuthors[7]],
    genres: [mockGenres[7], mockGenres[4]],
    tags: [mockTags[1], mockTags[5], mockTags[6]],
    averageRating: 4.8,
    reviewsCount: 567,
  },
  {
    id: 9,
    title: 'Вишневый сад',
    textFile: '/books/cherry-orchard.txt',
    coverFile: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Пьеса о разорении дворянской семьи и вырубке вишнёвого сада. Размышление о прошлом и будущем России.',
    authors: [mockAuthors[2]],
    genres: [mockGenres[0], mockGenres[4]],
    tags: [mockTags[1]],
    averageRating: 4.4,
    reviewsCount: 156,
  },
  {
    id: 10,
    title: 'Идиот',
    textFile: '/books/idiot.txt',
    coverFile: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
    description: 'Роман о князе Мышкине, человеке исключительной доброты в циничном обществе. Исследование природы добра и зла.',
    authors: [mockAuthors[0]],
    genres: [mockGenres[0], mockGenres[4]],
    tags: [mockTags[1], mockTags[2], mockTags[3]],
    averageRating: 4.7,
    reviewsCount: 234,
  },
];

export const mockUsers: User[] = [
  { id: 1, login: 'admin', email: 'admin@library.com', role: 'admin' },
  { id: 2, login: 'reader1', email: 'reader@example.com', role: 'client' },
  { id: 3, login: 'guest', email: '', role: 'guest' },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    userId: 2,
    userName: 'reader1',
    bookId: 1,
    rate: 5,
    text: 'Невероятная глубина психологического анализа! Каждый раз перечитываю и нахожу что-то новое.',
    createdAt: '2026-04-15',
  },
  {
    id: 2,
    userId: 1,
    userName: 'admin',
    bookId: 1,
    rate: 5,
    text: 'Шедевр мировой литературы. Обязательно к прочтению.',
    createdAt: '2026-04-10',
  },
  {
    id: 3,
    userId: 2,
    userName: 'reader1',
    bookId: 3,
    rate: 5,
    text: 'Булгаков создал нечто невероятное. Мистика, сатира, любовь - всё переплетено мастерски.',
    createdAt: '2026-04-20',
  },
  {
    id: 4,
    userId: 1,
    userName: 'admin',
    bookId: 6,
    rate: 5,
    text: 'The book that started it all. Magical, enchanting, and perfect for all ages.',
    createdAt: '2026-04-12',
  },
  {
    id: 5,
    userId: 2,
    userName: 'reader1',
    bookId: 7,
    rate: 5,
    text: 'Prophetic and terrifying. Orwell\'s vision of the future is more relevant than ever.',
    createdAt: '2026-04-18',
  },
];

export const mockReadingBooks: ReadingBook[] = [
  {
    bookId: 1,
    title: 'Преступление и наказание',
    coverFile: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    page: 125,
    lastOpened: '2026-04-26',
    progress: 35,
  },
  {
    bookId: 3,
    title: 'Мастер и Маргарита',
    coverFile: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
    page: 45,
    lastOpened: '2026-04-25',
    progress: 12,
  },
];

export const mockCollections: Collection[] = [
  {
    id: 1,
    title: 'Избранное',
    userId: 2,
    books: [
      {
        id: 1,
        title: 'Преступление и наказание',
        coverFile: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
        authors: ['Федор Достоевский'],
        averageRating: 4.8,
      },
      {
        id: 3,
        title: 'Мастер и Маргарита',
        coverFile: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
        authors: ['Михаил Булгаков'],
        averageRating: 4.9,
      },
    ],
  },
  {
    id: 2,
    title: 'Хочу прочитать',
    userId: 2,
    books: [
      {
        id: 2,
        title: 'Война и мир',
        coverFile: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
        authors: ['Лев Толстой'],
        averageRating: 4.7,
      },
    ],
  },
];
