// <auto-generated />
using System;
using Library.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.HasKey("BookId", "AuthorId")
                        .HasName("book_author_pkey");

                    b.HasIndex("AuthorId");

                    b.ToTable("book_author", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("BookId", "GenreId")
                        .HasName("book_genre_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("book_genre", (string)null);
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("BookId", "TagId")
                        .HasName("book_tag_pkey");

                    b.HasIndex("TagId");

                    b.ToTable("book_tag", (string)null);
                });

            modelBuilder.Entity("CollectionBook", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.HasKey("CollectionId", "BookId")
                        .HasName("collection_book_pkey");

                    b.HasIndex("BookId");

                    b.ToTable("collection_book", (string)null);
                });

            modelBuilder.Entity("FavouriteBook", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.HasKey("UserId", "BookId")
                        .HasName("favourite_book_pkey");

                    b.HasIndex("BookId");

                    b.ToTable("favourite_book", (string)null);
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("character varying")
                        .HasColumnName("bio");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("Authors_pkey");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CoverFile")
                        .HasColumnType("character varying")
                        .HasColumnName("cover_file");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("TextFile")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("text_file");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("Books_pkey");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Bookmark", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.HasKey("UserId", "BookId")
                        .HasName("Bookmarks_pkey");

                    b.HasIndex("BookId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Collection_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("Genres_pkey");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.ReadingBook", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<DateOnly>("LastOpened")
                        .HasColumnType("date")
                        .HasColumnName("last_opened");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.HasKey("UserId", "BookId")
                        .HasName("reading_book_pkey");

                    b.HasIndex("BookId");

                    b.ToTable("reading_book", (string)null);
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.Property<string>("ReviewText")
                        .HasColumnType("character varying")
                        .HasColumnName("review_text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Reviews_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("Roles_pkey");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("book_author_author_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("book_author_book_id_fkey");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("book_genre_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("book_genre_genre_id_fkey");
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("book_tag_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("book_tag_tag_id_fkey");
                });

            modelBuilder.Entity("CollectionBook", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("collection_book_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .IsRequired()
                        .HasConstraintName("collection_book_collection_id_fkey");
                });

            modelBuilder.Entity("FavouriteBook", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("favourite_book_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("favourite_book_user_id_fkey");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Bookmark", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("Bookmarks_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Bookmarks_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Collection", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Collection_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.ReadingBook", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", "Book")
                        .WithMany("ReadingBooks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("reading_book_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.User", "User")
                        .WithMany("ReadingBooks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("reading_book_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("Reviews_book_id_fkey");

                    b.HasOne("Library.Infrastructure.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Reviews_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.User", b =>
                {
                    b.HasOne("Library.Infrastructure.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Book", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("ReadingBooks");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Library.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Collections");

                    b.Navigation("ReadingBooks");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
